### ISSUE TITLE
 error when running your code

### ISSUE THREAD

**Issue by abhi1607IIT** [kellenschmidt/Flight-Planner#1]
/tmp/cc3JcW5S.o: In function `main':
main.cpp:(.text+0x33): undefined reference to `FlightPlanner::FlightPlanner()'
main.cpp:(.text+0x82): undefined reference to `FlightPlanner::readFlightData(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
main.cpp:(.text+0xef): undefined reference to `FlightPlanner::openOutputFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
main.cpp:(.text+0x15c): undefined reference to `FlightPlanner::readFlightPlans(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
main.cpp:(.text+0x189): undefined reference to `FlightPlanner::closeFiles()'
collect2: error: ld returned 1 exit status

**Comment by kellenschmidt** [comment]
Could you give me some more information about this issue? Such as what test files you were using?Hopefully we can get to the bottom of it!

**Comment by abhi1607IIT** [comment]
In your code main function is not being compiled  via g++ main.cpp  and
give errors . It is not able to open input files . Can you help.

**Comment by abhi1607IIT** [comment]
http://www.cse.iitd.ernet.in/~naveen/courses/CSL201J/assgn6.html.   Can you help in coding it

**Comment by abhi1607IIT** [comment]
Can you clearly specify how to run your program

**Comment by kellenschmidt** [comment]
Yeah absolutely I can help you. Do you have Venmo?

**Comment by abhi1607IIT** [comment]
Can you make a simple code that just outputs the min cost as said by the
question

**Comment by abhi1607IIT** [comment]
Noi don't have Venmo

**Comment by kellenschmidt** [comment]
Uh no I'm not going to do your homework for you. Do your own homework.😑

**Comment by abhi1607IIT** [comment]
You can atleast  tell why your code is not able to compile . Rest I can do
on my own.

On Nov 12, 2017 10:07 AM, "Kellen Schmidt" <notifications@github.com> wrote:

Uh no I'm not going to do your homework for you. Do your own homework.😑

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/kellenschmidt/Flight-Planner/issues/1#issuecomment-343713011>,
or mute the thread

**Comment by kellenschmidt** [comment]
If you want to send me some money and I'll help you get my code running on your machine

**Comment by abhi1607IIT** [comment]
It is not identifying FlightPlanner object in main and also not able to
open input files

**Comment by abhi1607IIT** [comment]
How much do you want ?

**Comment by abhi1607IIT** [comment]
If I can afford I surely will

**Comment by kellenschmidt** [comment]
10,000 Rupees
